
#define I2C_DEVICE_FEEDER   1
#define I2C_DEVICE_PUMPS    1

#define I2C_CMD_FEEDER_RUN        1
#define I2C_CMD_FEEDER_LOAD_COAL  2

#define I2C_CMD_GENERAL_WORKMODE    20
#define I2C_CMD_GENERAL_GET_PARAM   21
#define I2C_CMD_GENERAL_SET_PARAM   22
